apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::672346384212:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-FLOUJ07PEERD
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-10T08:46:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "819"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 002aefbf-adea-4e34-94cc-43d114114329
